name: Sync to Dev Repos

on:
  push:
    branches:
      - master

jobs:
  sync:
    run-on: ubuntu-latest

  steps:
    - name: Setup SSH Lev
      run:  |
        mkdir -p ~/.ssh
        echo "${{ SSH_PRIVATE_KEY_LEV }}" > ~/.ssh/id_rsa_lev
        chmod 600 ~/ssh/id_rsa_lev
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push to Dev lev
      run: |
        git remote add github-lev git@github.com:LevPavelko/Agora.WebAPI.git
        git push github-lev master
    

    - name: Setup SSH Irina
      run:  |
        mkdir -p ~/.ssh
        echo "${{ SSH_PRIVATE_KEY_IRINA }}" > ~/.ssh/id_rsa_irina
        chmod 600 ~/ssh/id_rsa_irina
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push to Dev Irina
      run: |
        git remote add github-irina git@github.com:IrynaKonovalowa/AgoraWebAPI.git
        git push github-irina master

    - name: Setup SSH Anastasia
      run:  |
        mkdir -p ~/.ssh
        echo "${{ SSH_PRIVATE_KEY_ANASTASIA }}" > ~/.ssh/id_rsa_nastasia
        chmod 600 ~/ssh/id_rsa_nastasia
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push to Dev Anastasia
      run: |
        git remote add git@github.com:AnastasiaSchull/Agora.WebAPI.git
        git push github-nastasia master

    - name: Setup SSH Vladyslav
      run:  |
        mkdir -p ~/.ssh
        echo "${{ SSH_PRIVATE_KEY_VLADYSLAV }}" > ~/.ssh/id_rsa_vlad
        chmod 600 ~/ssh/id_rsa_vlad
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push to Dev Vladyslav
      run: |
        git remote add github-vlad git@github.com:SerdiukVladyslav/VladTest.git
        git push github-vlad master
